qlblock:
  peer:
    seednode:
      ip: 127.0.0.1
      port: 8002
    ip: 127.0.0.1
    port: 8002
    version: 0.0.1-SNAPSHOT
server:
  port: 8080
spring:
  cache:
    type: redis
    redis:
      cache-null-values: true
  redis:
    redisson:
      config: classpath:redisson.yml
