qlblock:
  peer:
    seednode:
      ip: 127.0.0.1
      port: 8001
    ip: 127.0.0.1
    port: 8001
    version: 0.0.1-SNAPSHOT
  ledger:
    wallet:
      key: 2RxV4m78RGjpDZ5VV6TTtkSkRKgEC58qoYKq5rA4jkjPUbhnEd9iLUdr178PgxWaQKjjfhVscPfxo8qGAJwqZTjn1bL5
  sys:
    log:
      ismintprocess: no
server:
  port: 8081
