qlblock:
  peer:
    seednode:
      ip: 127.0.0.1
      port: 8001
    ip: 127.0.0.1
    port: 8001
    version: 0.0.1-SNAPSHOT
  ledger:
    wallet:
      key: 2RxV4m78RGjpDZ5VV6TTtkSkRKgEC58qoYKq5rA4jkjPUbhnCXU6Uq3a9y6kq3eMgse9hWHTFDkVWPeisyzuXANQ95fQ
  sys:
    log:
      ismintprocess: yes
  consensus:
    performanceOccupy: 0.1%
    isMinter: no
server:
  port: 8081
